apiVersion: v1
kind: Service
metadata:
  name: pe-intern-testing-deployment
  labels:
    app.kubernetes.io/name: pe-intern-testing-deployment
spec:
  selector:
    app.kubernetes.io/name: pe-intern-testing-deployment
  ports:
    - name: http
      port: 80
      targetPort: http
